ContosoUniversity/ContosoUniversity/Controllers/ToDoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ContosoUniversity.Data;
using ContosoUniversity.Models;

namespace ContosoUniversity.Controllers
{
    public class ToDoController : Controller
    {
        private readonly SchoolContext _context;

        public ToDoController(SchoolContext context)
        {
            _context = context;    
        }

        //public IActionResult Index2()
        //{
        //    var model = _context.TodoItems.ToList();
        //    return View(model);
        //}
        #region snippet_IndexVC
        public IActionResult ViewComponentFromController()
        {
            return ViewComponent("PriorityList", new { maxPriority = 10, isDone = false });
        }
        #endregion

        public async Task<IActionResult> IndexFinal()
        {
            return View(await _context.TodoItems.ToListAsync());
        }

        public IActionResult IndexNameof()
        {
            return View(_context.TodoItems.ToList());
        }

        public IActionResult IndexFirst()
        {
            return View(_context.TodoItems.ToList());
        }


        // GET: ToDo
        public async Task<IActionResult> Index()
        {
            return View(await _context.TodoItems.ToListAsync());
        }

        // GET: ToDo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoItem = await _context.TodoItems
                .SingleOrDefaultAsync(m => m.Id == id);
            if (todoItem == null)
            {
                return NotFound();
            }

            return View(todoItem);
        }

        // GET: ToDo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ToDo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Priority,IsDone")] TodoItem todoItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(todoItem);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(todoItem);
        }

        // GET: ToDo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoItem = await _context.TodoItems.SingleOrDefaultAsync(m => m.Id == id);
            if (todoItem == null)
            {
                return NotFound();
            }
            return View(todoItem);
        }

        // POST: ToDo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Priority,IsDone")] TodoItem todoItem)
        {
            if (id != todoItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(todoItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TodoItemExists(todoItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(todoItem);
        }

        // GET: ToDo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoItem = await _context.TodoItems
                .SingleOrDefaultAsync(m => m.Id == id);
            if (todoItem == null)
            {
                return NotFound();
            }

            return View(todoItem);
        }

        // POST: ToDo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var todoItem = await _context.TodoItems.SingleOrDefaultAsync(m => m.Id == id);
            _context.TodoItems.Remove(todoItem);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool TodoItemExists(int id)
        {
            return _context.TodoItems.Any(e => e.Id == id);
        }
    }
}

ContosoUniversity/ContosoUniversity/ViewComponents/PriorityListViewComponent.cs
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.ViewComponents
{
    public class PriorityListViewComponent : ViewComponent
    {
        private readonly SchoolContext _context;
        public PriorityListViewComponent(SchoolContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int maxPriority, bool isDone)
        {
            string myView = "Default";

            // If asking for all completed tasks, render with the "PVCCompleted" view
            if(isDone == true)
            {
                myView = "PVCCompleted";
            }
            var items = await GetItemAsync(maxPriority, isDone);
            return View(myView, items);
        }

        private Task<List<TodoItem>> GetItemAsync(int maxPriority, bool isDone)
        {
            return _context.TodoItems.Where(x => x.IsDone == isDone && x.Priority <= maxPriority).ToListAsync();
        }
    }
}

ContosoUniversity/ContosoUniversity/Views/ToDo/Create.cshtml
@model ContosoUniversity.Models.TodoItem

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>TodoItem</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Priority" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Priority" class="form-control" />
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="IsDone" />
                    <label asp-for="IsDone"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ContosoUniversity/ContosoUniversity/Views/ToDo/Delete.cshtml
@model ContosoUniversity.Models.TodoItem

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TodoItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="Id" />
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

ContosoUniversity/ContosoUniversity/Views/ToDo/Details.cshtml
@model ContosoUniversity.Models.TodoItem

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>TodoItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ContosoUniversity/ContosoUniversity/Views/ToDo/Edit.cshtml
@model ContosoUniversity.Models.TodoItem

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>TodoItem</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Priority" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Priority" class="form-control" />
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="IsDone" />
                    <label asp-for="IsDone"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ContosoUniversity/ContosoUniversity/Views/ToDo/Index.cshtml
@model IEnumerable<ContosoUniversity.Models.TodoItem>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Priority)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsDone)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Priority)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDone)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    @await  Component.InvokeAsync("PriorityList", new { maxPriority = 13, isDone = true})
</div>